id = "zed-haxe"
name = "Haxe"
version = "0.0.2"
schema_version = 1
authors = ["Cameron Taylor <cameron.taylor.ninja@gmail.com>"]
description = "Haxe Tree Sitter for Zed"
repository = "https://github.com/ninjamuffin99/zed-haxe"

[grammars.haxe]
repository = "https://github.com/vantreeseba/tree-sitter-haxe"
commit = "12e814cd9b0656b0eaa3e04b0036b3b6625cc0d7"
